export const LOAD_CALENDAR_PAGE_SAGA = 'TYPE_ACTION_LOAD_CALENDAR_PAGE_SAGA';

export const ON_ACCEPT_CALENDAR_PAGE_DIALOG_SAGA =
  'ON_ACCEPT_CALENDAR_PAGE_DIALOG_SAGA';

export const ON_CLOSE_CALENDAR_PAGE_DIALOG_SAGA =
  'ON_CLOSE_CALENDAR_PAGE_DIALOG_SAGA';

export const ON_OPEN_CALENDAR_PAGE_DIALOG_SAGA =
  'ON_OPEN_CALENDAR_PAGE_DIALOG_SAGA';

export const LOAD_CALENDAR_WEATHER_INFO = 'ACTION_LOAD_CALENDAR_WEATHER_INFO';

export const ON_SEARCH_CITY_SAGA = 'ON_SEARCH_CITY_SAGA';
export const CLEAR_CITY_OPTION_SAGA = 'CLEAR_CITY_OPTION_SAGA';
